import { SourceProvider } from '../entities/source.entity';

export interface SourceSeedItem {
  provider: SourceProvider;
  externalId: string;
  name: string;
}

export const sourceSeeds: SourceSeedItem[] = [
  { provider: SourceProvider.ASHBY, externalId: 'n8n', name: 'n8n' },
  { provider: SourceProvider.ASHBY, externalId: 'gorgias', name: 'Gorgias' },
  { provider: SourceProvider.ASHBY, externalId: 'passport', name: 'Passport' },
  { provider: SourceProvider.ASHBY, externalId: 'oakslab', name: "OAK'S LAB" },
  { provider: SourceProvider.ASHBY, externalId: 'space44', name: 'Space44' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'perplexity',
    name: 'Perplexity',
  },
  { provider: SourceProvider.ASHBY, externalId: 'rho', name: 'Rho' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'ruby-labs',
    name: 'Ruby Labs',
  },
  { provider: SourceProvider.ASHBY, externalId: 'deel', name: 'Deel' },

  { provider: SourceProvider.ASHBY, externalId: 'ramp', name: 'Ramp' },
  { provider: SourceProvider.ASHBY, externalId: 'cognition', name: 'Cognition' },
  { provider: SourceProvider.ASHBY, externalId: 'suno', name: 'Suno' },
  { provider: SourceProvider.ASHBY, externalId: 'brainco', name: 'BrainCo' },
  { provider: SourceProvider.ASHBY, externalId: 'notion', name: 'Notion' },
  { provider: SourceProvider.ASHBY, externalId: 'baseten', name: 'Baseten' },
  { provider: SourceProvider.ASHBY, externalId: 'substack', name: 'Substack' },
  { provider: SourceProvider.ASHBY, externalId: 'cluely', name: 'Cluely' },
  { provider: SourceProvider.ASHBY, externalId: 'everis', name: 'Everis' },
  { provider: SourceProvider.ASHBY, externalId: 'vibe', name: 'Vibe' },
  { provider: SourceProvider.ASHBY, externalId: 'sierra', name: 'Sierra' },
  { provider: SourceProvider.ASHBY, externalId: 'cohere', name: 'Cohere' },
  { provider: SourceProvider.ASHBY, externalId: 'supabase', name: 'Supabase' },
  { provider: SourceProvider.ASHBY, externalId: 'norm-ai', name: 'Norm AI' },
  { provider: SourceProvider.ASHBY, externalId: 'atticus', name: 'Atticus' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'develop-health',
    name: 'Develop Health',
  },
  { provider: SourceProvider.ASHBY, externalId: 'tenexlabs', name: 'Tenex Labs' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'ironcladhq',
    name: 'Ironclad',
  },
  { provider: SourceProvider.ASHBY, externalId: 'valon', name: 'Valon' },
  { provider: SourceProvider.ASHBY, externalId: 'mercor', name: 'Mercor' },
  { provider: SourceProvider.ASHBY, externalId: 'kalshi', name: 'Kalshi' },
  { provider: SourceProvider.ASHBY, externalId: 'auctor', name: 'Auctor' },
  { provider: SourceProvider.ASHBY, externalId: 'modernfi', name: 'ModernFi' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'mechanize',
    name: 'Mechanize',
  },
  { provider: SourceProvider.ASHBY, externalId: 'zania', name: 'Zania' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'adaptivesecurity',
    name: 'Adaptive Security',
  },
  { provider: SourceProvider.ASHBY, externalId: 'tandem', name: 'Tandem' },
  { provider: SourceProvider.ASHBY, externalId: 'replit', name: 'Replit' },
  { provider: SourceProvider.ASHBY, externalId: 'middesk', name: 'Middesk' },
  { provider: SourceProvider.ASHBY, externalId: 'sesame', name: 'Sesame' },
  { provider: SourceProvider.ASHBY, externalId: 'opal', name: 'Opal' },
  { provider: SourceProvider.ASHBY, externalId: 'rillet', name: 'Rillet' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'benchling',
    name: 'Benchling',
  },
  { provider: SourceProvider.ASHBY, externalId: 'eliseai', name: 'Elise AI' },

  { provider: SourceProvider.ASHBY, externalId: 'rain', name: 'Rain' },
  { provider: SourceProvider.ASHBY, externalId: 'junior', name: 'Junior' },
  { provider: SourceProvider.ASHBY, externalId: 'echomark', name: 'Echomark' },
  { provider: SourceProvider.ASHBY, externalId: 'grepr', name: 'Grepr' },
  { provider: SourceProvider.ASHBY, externalId: 'bevel', name: 'Bevel' },
  { provider: SourceProvider.ASHBY, externalId: 'sentient', name: 'Sentient' },
  { provider: SourceProvider.ASHBY, externalId: 'tennr', name: 'Tennr' },
  { provider: SourceProvider.ASHBY, externalId: 'happl', name: 'Happl' },
  { provider: SourceProvider.ASHBY, externalId: 'nash', name: 'Nash' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'talentsafari',
    name: 'Talent Safari',
  },
  { provider: SourceProvider.ASHBY, externalId: 'exa', name: 'Exa' },
  { provider: SourceProvider.ASHBY, externalId: 'litellm', name: 'LiteLLM' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'anything',
    name: 'Anything',
  },
  { provider: SourceProvider.ASHBY, externalId: 'tango', name: 'Tango' },
  { provider: SourceProvider.ASHBY, externalId: 'krea', name: 'Krea' },
  { provider: SourceProvider.ASHBY, externalId: 'coderabbit', name: 'CodeRabbit' },
  { provider: SourceProvider.ASHBY, externalId: 'ivo-inc', name: 'Ivo' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'fundamental',
    name: 'Fundamental',
  },
  { provider: SourceProvider.ASHBY, externalId: 'sardine', name: 'Sardine' },
  { provider: SourceProvider.ASHBY, externalId: 'kraken', name: 'Kraken' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'uncountable',
    name: 'Uncountable',
  },
  { provider: SourceProvider.ASHBY, externalId: 'hudu', name: 'Hudu' },
  { provider: SourceProvider.ASHBY, externalId: 'zowie', name: 'Zowie' },
  { provider: SourceProvider.ASHBY, externalId: 'xpreso', name: 'Xpreso' },
  { provider: SourceProvider.ASHBY, externalId: 'phonely', name: 'Phonely' },
  { provider: SourceProvider.ASHBY, externalId: 'colonist', name: 'Colonist' },
  { provider: SourceProvider.ASHBY, externalId: 'speak', name: 'Speak' },
  { provider: SourceProvider.ASHBY, externalId: 'acorns', name: 'Acorns' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'nord-security',
    name: 'Nord Security',
  },
  { provider: SourceProvider.ASHBY, externalId: 'NationGraph', name: 'NationGraph' },
  { provider: SourceProvider.ASHBY, externalId: 'assured', name: 'Assured' },
  { provider: SourceProvider.ASHBY, externalId: 'scribe', name: 'Scribe' },
  { provider: SourceProvider.ASHBY, externalId: 'bio', name: 'Bio' },
  { provider: SourceProvider.ASHBY, externalId: 'mexdigital', name: 'MexDigital' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'junipersquare',
    name: 'Juniper Square',
  },
  { provider: SourceProvider.ASHBY, externalId: 'sweedpos.com', name: 'Sweed' },
  { provider: SourceProvider.ASHBY, externalId: 'flipper', name: 'Flipper' },
  { provider: SourceProvider.ASHBY, externalId: 'known', name: 'Known' },
  { provider: SourceProvider.ASHBY, externalId: 'sana-roles', name: 'Sana' },
  { provider: SourceProvider.ASHBY, externalId: 'togal-ai', name: 'Togal AI' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'polymarket',
    name: 'Polymarket',
  },
  { provider: SourceProvider.ASHBY, externalId: 'hiive', name: 'Hiive' },
  { provider: SourceProvider.ASHBY, externalId: 'kestra', name: 'Kestra' },
  { provider: SourceProvider.ASHBY, externalId: 'dash0', name: 'Dash0' },
  { provider: SourceProvider.ASHBY, externalId: 'jellyfish', name: 'Jellyfish' },
  { provider: SourceProvider.ASHBY, externalId: 'glide', name: 'Glide' },
  { provider: SourceProvider.ASHBY, externalId: 'odyssey', name: 'Odyssey' },
  { provider: SourceProvider.ASHBY, externalId: 'phia', name: 'Phia' },
  { provider: SourceProvider.ASHBY, externalId: 'roboflow', name: 'Roboflow' },
  { provider: SourceProvider.ASHBY, externalId: 'infisical', name: 'Infisical' },
  { provider: SourceProvider.ASHBY, externalId: 'adonis', name: 'Adonis' },
  { provider: SourceProvider.ASHBY, externalId: 'lightfield', name: 'Lightfield' },
  { provider: SourceProvider.ASHBY, externalId: 'gumloop', name: 'Gumloop' },
  { provider: SourceProvider.ASHBY, externalId: 'tem', name: 'Tem' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'wynd-labs',
    name: 'Wynd Labs',
  },
  { provider: SourceProvider.ASHBY, externalId: 'rootglobal', name: 'Root Global' },
  { provider: SourceProvider.ASHBY, externalId: 'resq', name: 'ResQ' },
  { provider: SourceProvider.ASHBY, externalId: 'ocra', name: 'Ocra' },
  { provider: SourceProvider.ASHBY, externalId: 'sift', name: 'Sift' },
  { provider: SourceProvider.ASHBY, externalId: 'fluency', name: 'Fluency' },
  { provider: SourceProvider.ASHBY, externalId: 'feathery', name: 'Feathery' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'the-flex',
    name: 'The Flex',
  },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'tensorwave',
    name: 'TensorWave',
  },
  { provider: SourceProvider.ASHBY, externalId: 'ekho', name: 'Ekho' },
  { provider: SourceProvider.ASHBY, externalId: 'flankai', name: 'Flank AI' },
  { provider: SourceProvider.ASHBY, externalId: 'partiful', name: 'Partiful' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'blacksmith',
    name: 'Blacksmith',
  },
  { provider: SourceProvider.ASHBY, externalId: 'magentic', name: 'Magentic' },
  { provider: SourceProvider.ASHBY, externalId: 'conduct', name: 'Conduct' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'usekernel',
    name: 'UseKernel',
  },
  { provider: SourceProvider.ASHBY, externalId: 'scrunch', name: 'Scrunch' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'relevanceai',
    name: 'Relevance AI',
  },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'velocity',
    name: 'Velocity',
  },
  { provider: SourceProvider.ASHBY, externalId: 'warp', name: 'Warp' },
  { provider: SourceProvider.ASHBY, externalId: 'paraform', name: 'Paraform' },
  { provider: SourceProvider.ASHBY, externalId: 'workos', name: 'WorkOS' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'sequence',
    name: 'Sequence',
  },
  { provider: SourceProvider.ASHBY, externalId: 'sphinx', name: 'Sphinx' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'junction',
    name: 'Junction',
  },
  { provider: SourceProvider.ASHBY, externalId: 'g2i', name: 'G2i' },
  { provider: SourceProvider.ASHBY, externalId: 'somethings', name: 'Somethings' },
  { provider: SourceProvider.ASHBY, externalId: 'vega', name: 'Vega' },
  { provider: SourceProvider.ASHBY, externalId: 'ether.fi', name: 'Ether.fi' },
  { provider: SourceProvider.ASHBY, externalId: 'backpack', name: 'Backpack' },
  { provider: SourceProvider.ASHBY, externalId: 'vanilla', name: 'Vanilla' },
  { provider: SourceProvider.ASHBY, externalId: 'hiverge', name: 'Hiverge' },
  { provider: SourceProvider.ASHBY, externalId: 'st-labs', name: 'ST Labs' },
  { provider: SourceProvider.ASHBY, externalId: 'pawchamp', name: 'PawChamp' },
  { provider: SourceProvider.ASHBY, externalId: 'luxor', name: 'Luxor' },
  { provider: SourceProvider.ASHBY, externalId: 'kong', name: 'Kong' },
  { provider: SourceProvider.ASHBY, externalId: 'skelar', name: 'Skelar' },
  { provider: SourceProvider.ASHBY, externalId: 'solidgate', name: 'Solidgate' },
  { provider: SourceProvider.ASHBY, externalId: 'lendable', name: 'Lendable' },
  { provider: SourceProvider.ASHBY, externalId: 'rebuy', name: 'Rebuy' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'hawkeyeinnovations',
    name: 'Hawk-Eye Innovations',
  },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'wearebeyondsports',
    name: 'Beyond Sports',
  },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'leantechniques',
    name: 'Lean Techniques',
  },
  { provider: SourceProvider.ASHBY, externalId: 'cygnify', name: 'Cygnify' },
  { provider: SourceProvider.ASHBY, externalId: 'kontakt', name: 'Kontakt' },
  { provider: SourceProvider.ASHBY, externalId: 'seon', name: 'SEON' },
  { provider: SourceProvider.ASHBY, externalId: 'truelogic', name: 'Truelogic' },
  { provider: SourceProvider.ASHBY, externalId: 'sofarocean', name: 'Sofar Ocean' },
  { provider: SourceProvider.ASHBY, externalId: 'moab', name: 'Moab' },
  { provider: SourceProvider.ASHBY, externalId: 'juicebox', name: 'Juicebox' },
  { provider: SourceProvider.ASHBY, externalId: 'two-dots', name: 'Two Dots' },
  { provider: SourceProvider.ASHBY, externalId: 'vetcove', name: 'Vetcove' },
  { provider: SourceProvider.ASHBY, externalId: 'imprint', name: 'Imprint' },
  { provider: SourceProvider.ASHBY, externalId: 'camber', name: 'Camber' },
  { provider: SourceProvider.ASHBY, externalId: 'traba', name: 'Traba' },
  { provider: SourceProvider.ASHBY, externalId: 'brellium', name: 'Brellium' },
  { provider: SourceProvider.ASHBY, externalId: 'owner', name: 'Owner' },
  { provider: SourceProvider.ASHBY, externalId: 'cleric', name: 'Cleric' },
  { provider: SourceProvider.ASHBY, externalId: 'dust', name: 'Dust' },

  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'telesign',
    name: 'TeleSign',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'brainrocketltd',
    name: 'BrainRocket',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'sofiastars',
    name: 'Sofia Stars',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'databricks',
    name: 'Databricks',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'fireblocks',
    name: 'Fireblocks',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'gitlab', name: 'GitLab' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'speechify',
    name: 'Speechify',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'learnupon',
    name: 'LearnUpon',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'typeform',
    name: 'Typeform',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'spacex', name: 'SpaceX' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'florencehealthcare',
    name: 'Florence Healthcare',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'constructorknowledge',
    name: 'Constructor Knowledge',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'chainguard',
    name: 'Chainguard',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'recursionpharmaceuticals',
    name: 'Recursion Pharmaceuticals',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'distantjob',
    name: 'DistantJob',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'pointwild',
    name: 'PointWild',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'neoris',
    name: 'NEORIS',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'andurilindustries',
    name: 'Anduril Industries',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'singlestore',
    name: 'SingleStore',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'neo4j',
    name: 'Neo4j',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'equilibriumenergy',
    name: 'Equilibrium Energy',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'wheely',
    name: 'Wheely',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'faire',
    name: 'Faire',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'caronsale',
    name: 'CarOnSale',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'tvscientificpoweredbypinterest',
    name: 'TV Scientific',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'dv01',
    name: 'dv01',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'tailscale',
    name: 'Tailscale',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'crunchyroll',
    name: 'Crunchyroll',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'oura',
    name: 'Oura',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'rhinofederatedcomputing',
    name: 'Rhino Federated Computing',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'nice', name: 'Nice' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'ecoatmgazelle',
    name: 'ecoATM Gazelle',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'navvis', name: 'NavVis' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'brandwatch',
    name: 'Brandwatch',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'veeamsoftware',
    name: 'Veeam',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'delphiconsulting',
    name: 'Delphi Consulting',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'corelight', name: 'Corelight' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'kerv', name: 'Kerv' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'nearform', name: 'Nearform' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'shifttechnology',
    name: 'Shift Technology',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'justmarkets',
    name: 'JustMarkets',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'betsson', name: 'Betsson' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'abacusinsights',
    name: 'Abacus Insights',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'terrapowerllc',
    name: 'TerraPower',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'boku', name: 'Boku' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'neuraflash',
    name: 'NeuraFlash',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'calendly',
    name: 'Calendly',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'cycles', name: 'Cycles' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'particle41llc',
    name: 'Particle41',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'mightynetworks',
    name: 'Mighty Networks',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'paradigminccareersopenpositions',
    name: 'Paradigm',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'processstreet',
    name: 'Process Street',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'unanet', name: 'Unanet' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'nuitee', name: 'Nuitee' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'prolific',
    name: 'Prolific',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'vast', name: 'Vast' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'xai', name: 'xAI' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'tangoio', name: 'Tango' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'superbet', name: 'Superbet' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'hark', name: 'Hark' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'okx', name: 'OKX' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'nerdy', name: 'Nerdy' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'blockchain',
    name: 'Blockchain.com',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'headquarters',
    name: 'HeadQuarters',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'flosum',
    name: 'Flosum',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'gomining',
    name: 'GoMining',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'devpro',
    name: 'Dev.Pro',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'fioneer',
    name: 'SAP Fioneer',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'huggingface',
    name: 'Hugging Face',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'rokt', name: 'Rokt' },
  { provider: SourceProvider.WORKABLE, externalId: 'v4c', name: 'V4C' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'movement-labs',
    name: 'Movement Labs',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'enable-data',
    name: 'Enable Data',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'verneek', name: 'Verneek' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'keepsafe',
    name: 'Keepsafe',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'mlabs', name: 'MLabs' },
  { provider: SourceProvider.WORKABLE, externalId: 'otiv', name: 'Otiv' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'blueprint-bryanjohnson',
    name: 'Blueprint (Bryan Johnson)',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'aureol-global-connections',
    name: 'Aureol Global Connections',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'suade', name: 'Suade' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'civica-uk-ltd-1',
    name: 'Civica UK',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'portless',
    name: 'Portless',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'ordermesh',
    name: 'Ordermesh',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'translution-software',
    name: 'Translution Software',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'newrich-network',
    name: 'NewRich Network',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'destinusgroup',
    name: 'Destinus Group',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'goodvision',
    name: 'GoodVision',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'everypay-1',
    name: 'EveryPay',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'devsinc-17',
    name: 'Devsinc',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'openbet-1',
    name: 'OpenBet',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'upsmith-1',
    name: 'Upsmith',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'pubgenius-1',
    name: 'PubGenius',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'writesonic',
    name: 'Writesonic',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'goodfit',
    name: 'GoodFit',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'curology',
    name: 'Curology',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'servant',
    name: 'Servant',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'kupa-global',
    name: 'Kupa Global',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'maxana', name: 'Maxana' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'pulse-labs',
    name: 'Pulse Labs',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'gotymex',
    name: 'GoTymex',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'hilobyaktiia',
    name: 'Hilo by Axtiia',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'architus',
    name: 'Architus',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'constructor-1',
    name: 'Constructor',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'degica-hiring',
    name: 'Degica',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'cogna', name: 'Cogna' },
  { provider: SourceProvider.WORKABLE, externalId: 'akeno', name: 'Akeno' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'fuseenergy',
    name: 'Fuse Energy',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'helloaoa',
    name: 'Hello AOA',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'alfadocs',
    name: 'AlfaDocs',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'walletconnect',
    name: 'WalletConnect',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'flowdesk',
    name: 'Flowdesk',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'withplum',
    name: 'WithPlum',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'pavago', name: 'Pavago' },
  { provider: SourceProvider.WORKABLE, externalId: 'finartix', name: 'Finartix' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'hrfactory-lithuania',
    name: 'HR Factory Lithuania',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'methods', name: 'Methods' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'xolo-careers',
    name: 'Xolo',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'vecten', name: 'Vecten' },
  { provider: SourceProvider.WORKABLE, externalId: '28stone', name: '28Stone' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'dsquares-loyalty-dmcc',
    name: 'Dsquares Loyalty DMCC',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'justone-gr',
    name: 'JustOne',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'triglocon', name: 'Triglocon' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'telestream',
    name: 'Telestream',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'therapynotes',
    name: 'TherapyNotes',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'serva', name: 'Serva' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'tecknoworks',
    name: 'Tecknoworks',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'faircom', name: 'FairCom' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'colibrix-one',
    name: 'Colibrix One',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'airhelp', name: 'AirHelp' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'clearjunction',
    name: 'Clear Junction',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'zipdev', name: 'Zipdev' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'thepixelocracy',
    name: 'The Pixelocracy',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'hulcan', name: 'Hulcan' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'skylight-frame',
    name: 'Skylight Frame',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'a2mac1', name: 'A2MAC1' },
  { provider: SourceProvider.WORKABLE, externalId: 'connexity', name: 'Connexity' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'languagewire',
    name: 'LanguageWire',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'lago-1', name: 'Lago' },
  { provider: SourceProvider.WORKABLE, externalId: 'verisian', name: 'Verisian' },
  { provider: SourceProvider.WORKABLE, externalId: 'sans-2', name: 'Sans' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'virallens',
    name: 'Virallens',
  },
  { provider: SourceProvider.WORKABLE, externalId: '1kosmos', name: '1Kosmos' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'walter-careers',
    name: 'Walter',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'pearltalent',
    name: 'Pearl Talent',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'creativechaos',
    name: 'Creative Chaos',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'enzari', name: 'Enzari' },
  { provider: SourceProvider.WORKABLE, externalId: 'aerones', name: 'Aerones' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'jagex-limited',
    name: 'Jagex',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'quantumloopai',
    name: 'Quantum Loop AI',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'pix4d', name: 'Pix4D' },
  { provider: SourceProvider.WORKABLE, externalId: 'ldms', name: 'LDMS' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'xcelirate',
    name: 'Xcelirate',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'ki-insurance',
    name: 'Ki Insurance',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'quadric-dot-i-o-inc',
    name: 'Quadric',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'exec', name: 'Exec' },
  { provider: SourceProvider.WORKABLE, externalId: 'delli', name: 'Delli' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'weekday-1',
    name: 'Weekday',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'panorama-education',
    name: 'Panorama Education',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'vvd', name: 'VVD' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'elevate-semiconductor',
    name: 'Elevate Semiconductor',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'cloudlinux-1',
    name: 'CloudLinux',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'whiteshield',
    name: 'WhiteShield',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'open-252', name: 'Open' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'realyse-1',
    name: 'Realyse',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'smarttechsa',
    name: 'SmartTech SA',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'portswigger',
    name: 'PortSwigger',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'gsstech-group',
    name: 'GSS Tech Group',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'valsoft-corp',
    name: 'Valsoft',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'fuku', name: 'Fuku' },
  { provider: SourceProvider.WORKABLE, externalId: 'teamified', name: 'Teamified' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'ninetwothree-ai-studio',
    name: 'NineTwoThree AI Studio',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'warden-ai',
    name: 'Warden AI',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'forefront-rf',
    name: 'Forefront RF',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'povio', name: 'Povio' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'vista-group',
    name: 'Vista Group',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'intetics-2',
    name: 'Intetics',
  },
  { provider: SourceProvider.WORKABLE, externalId: '1global', name: '1GLOBAL' },
  { provider: SourceProvider.WORKABLE, externalId: 'islacare', name: 'Islacare' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'workana-premium',
    name: 'Workana',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'epignosis',
    name: 'Epignosis',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'hack-the-box-ltd',
    name: 'Hack The Box',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'ardanis', name: 'Ardanis' },
  { provider: SourceProvider.WORKABLE, externalId: 'everwest', name: 'Everwest' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'umpisa-inc',
    name: 'Umpisa',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'spd-technology',
    name: 'SPD Technology',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'ethics-code',
    name: 'Ethics Code',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'storyteq', name: 'Storyteq' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'tp-link-usa-corp',
    name: 'TP-Link USA',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'youtapcareers',
    name: 'Youtap',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'spaceinch',
    name: 'Space Inch',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'minderacraft',
    name: 'Mindera',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'solirius-consulting-1',
    name: 'Solirius Consulting',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'solance', name: 'Solance' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'human-intelligence',
    name: 'Human Intelligence',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'azumo', name: 'Azumo' },
  { provider: SourceProvider.WORKABLE, externalId: 'ssc-hr', name: 'SSC HR' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'and-digital',
    name: 'AND Digital',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'uni-systems',
    name: 'Uni Systems',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'itrs', name: 'ITRS' },
  { provider: SourceProvider.WORKABLE, externalId: 'brixio', name: 'Brixio' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'mediaandgamesinvest',
    name: 'Media and Games Invest',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'owt-swiss',
    name: 'OWT Swiss',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'talentgratorjobs',
    name: 'Talentgrator',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'plainconcepts',
    name: 'Plain Concepts',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'agad-technology',
    name: 'Agad Technology',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'two95-international-inc-3',
    name: 'Two95 International',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'profile-sw',
    name: 'Profile Software',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'dacodes-mx', name: 'DaCodes' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'getvocal-ai',
    name: 'Vocal AI',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'resonance', name: 'Resonance' },
  { provider: SourceProvider.WORKABLE, externalId: 'dopay-8', name: 'dopay' },
  { provider: SourceProvider.WORKABLE, externalId: 'momos', name: 'Momos' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'crossbordertalents',
    name: 'Cross Border Talents',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'cleeng-1', name: 'Cleeng' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'cosmote-global-solutions-nv',
    name: 'COSMOTE Global Solutions',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'nogood', name: 'NoGood' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'mitratech', name: 'Mitratech' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'remotecom', name: 'Remote.com' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'cloudflare', name: 'Cloudflare' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'backblaze', name: 'Backblaze' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'cybermediatechnologies',
    name: 'Cybermedia Technologies',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'neweratechnology',
    name: 'New Era Technology',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'growetalents', name: 'Growe' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'touchbistro', name: 'TouchBistro' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'mithril', name: 'Mithril' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'optimove', name: 'Optimove' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'encora10', name: 'Encora' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'grvty', name: 'GRVTY' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'robinhood', name: 'Robinhood' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'growe', name: 'Growe' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'iconcareers', name: 'ICON' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'planetscale', name: 'PlanetScale' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'ably30', name: 'Ably' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'aloyoga', name: 'Alo Yoga' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'ntconcepts', name: 'NT Concepts' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'showpad', name: 'Showpad' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'appliedintuition',
    name: 'Applied Intuition',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'quantboxresearchpte',
    name: 'Quantbox Research',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'ecosio', name: 'ecosio' },
  { provider: SourceProvider.GREENHOUSE, externalId: '541', name: '541' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'genea', name: 'Genea' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'affirm', name: 'Affirm' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'arizeai', name: 'Arize AI' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'dexory', name: 'Dexory' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'worldquant', name: 'WorldQuant' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'point72', name: 'Point72' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'csciconsulting',
    name: 'CSCI Consulting',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'vmlenterprisesolutions',
    name: 'VML Enterprise Solutions',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'figma', name: 'Figma' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'next-internal',
    name: 'Next',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'defenseunicorns',
    name: 'Defense Unicorns',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'grahamcapitalmanagement',
    name: 'Graham Capital Management',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'defuselabs',
    name: 'Defuse Labs',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'accenturefederalservices',
    name: 'Accenture Federal Services',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'turnkeycareers',
    name: 'Turnkey',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'jetbrains', name: 'JetBrains' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'zencoder', name: 'Zencoder' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'valtech', name: 'Valtech' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'wargamingen',
    name: 'Wargaming',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'ocrolusinc', name: 'Ocrolus' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'garnerhealth', name: 'Garner Health' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'easyship', name: 'Easyship' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'fortrobotics',
    name: 'FORT Robotics',
  },
  { provider: SourceProvider.ASHBY, externalId: 'openai', name: 'OpenAI' },
  { provider: SourceProvider.ASHBY, externalId: '1password', name: '1Password' },
  { provider: SourceProvider.ASHBY, externalId: 'sciencelogic', name: 'ScienceLogic' },
  { provider: SourceProvider.ASHBY, externalId: 'langchain', name: 'LangChain' },
  { provider: SourceProvider.ASHBY, externalId: 'livekit', name: 'LiveKit' },
  { provider: SourceProvider.ASHBY, externalId: 'sunday', name: 'Sunday' },
  { provider: SourceProvider.ASHBY, externalId: 'dexmate', name: 'Dexmate' },
  { provider: SourceProvider.ASHBY, externalId: 'statsports', name: 'STATSports' },
  { provider: SourceProvider.ASHBY, externalId: 'bubble', name: 'Bubble' },
  { provider: SourceProvider.ASHBY, externalId: 'openrouter', name: 'OpenRouter' },
  { provider: SourceProvider.ASHBY, externalId: 'revenuecat', name: 'RevenueCat' },
  { provider: SourceProvider.ASHBY, externalId: 'weaviate', name: 'Weaviate' },
  { provider: SourceProvider.ASHBY, externalId: 'anrok', name: 'Anrok' },
  { provider: SourceProvider.ASHBY, externalId: 'browserbase', name: 'Browserbase' },
  { provider: SourceProvider.ASHBY, externalId: 'melotech', name: 'Melotech' },
  { provider: SourceProvider.ASHBY, externalId: 'koho', name: 'KOHO' },
  { provider: SourceProvider.ASHBY, externalId: 'equip', name: 'Equip' },
  { provider: SourceProvider.ASHBY, externalId: 'harvey', name: 'Harvey' },
  { provider: SourceProvider.ASHBY, externalId: 'claylabs', name: 'Clay' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'wallstreetbets',
    name: 'WallStreetBets',
  },
  { provider: SourceProvider.ASHBY, externalId: 'crosby', name: 'Crosby' },
  { provider: SourceProvider.ASHBY, externalId: 'anyscale', name: 'Anyscale' },
  { provider: SourceProvider.ASHBY, externalId: 'mapbox', name: 'Mapbox' },
  { provider: SourceProvider.ASHBY, externalId: 'decagon', name: 'Decagon' },
  { provider: SourceProvider.ASHBY, externalId: 'harmattan-ai', name: 'Harmattan AI' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'featherlessai',
    name: 'Featherless AI',
  },
  { provider: SourceProvider.ASHBY, externalId: 'synthesia', name: 'Synthesia' },
  { provider: SourceProvider.ASHBY, externalId: 'blp-digital', name: 'BLP Digital' },
  { provider: SourceProvider.ASHBY, externalId: 'vanta', name: 'Vanta' },
  { provider: SourceProvider.ASHBY, externalId: 'method-crm', name: 'Method CRM' },
  { provider: SourceProvider.ASHBY, externalId: 'smallpdf', name: 'Smallpdf' },
  { provider: SourceProvider.ASHBY, externalId: 'poesis', name: 'Poesis' },
  { provider: SourceProvider.ASHBY, externalId: 'jbs-dev', name: 'JBS Dev' },
  { provider: SourceProvider.ASHBY, externalId: 'prefect', name: 'Prefect' },
  { provider: SourceProvider.ASHBY, externalId: 'zip', name: 'Zip' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'hyperexponential',
    name: 'Hyperexponential',
  },
  { provider: SourceProvider.ASHBY, externalId: 'etched', name: 'Etched' },
  { provider: SourceProvider.ASHBY, externalId: 'reflow', name: 'Reflow' },
  { provider: SourceProvider.ASHBY, externalId: 'paddle', name: 'Paddle' },
  { provider: SourceProvider.ASHBY, externalId: 'sweep', name: 'Sweep' },
  { provider: SourceProvider.ASHBY, externalId: 'clickup', name: 'ClickUp' },
  { provider: SourceProvider.ASHBY, externalId: 'zapier', name: 'Zapier' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'interrahealth',
    name: 'Interra Health',
  },
  { provider: SourceProvider.ASHBY, externalId: 'govwell', name: 'GovWell' },
  { provider: SourceProvider.ASHBY, externalId: 'lapel', name: 'Lapel' },
  { provider: SourceProvider.ASHBY, externalId: 'optro', name: 'Optro' },
  { provider: SourceProvider.ASHBY, externalId: 'coder', name: 'Coder' },
  { provider: SourceProvider.ASHBY, externalId: 'pinecone', name: 'Pinecone' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'wealthsimple',
    name: 'Wealthsimple',
  },
  { provider: SourceProvider.ASHBY, externalId: 'uipath', name: 'UiPath' },
  { provider: SourceProvider.ASHBY, externalId: 'toms', name: "Tom's" },
  { provider: SourceProvider.ASHBY, externalId: 'ridealso', name: 'Ridealso' },
  { provider: SourceProvider.ASHBY, externalId: 'reaktor', name: 'Reaktor' },
  { provider: SourceProvider.ASHBY, externalId: 'gridcare', name: 'Gridcare' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'revenuebase-inc',
    name: 'RevenueBase',
  },
  { provider: SourceProvider.ASHBY, externalId: 'rapdev', name: 'RapDev' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'polygon-labs',
    name: 'Polygon Labs',
  },
  { provider: SourceProvider.ASHBY, externalId: 'loora', name: 'Loora' },
  { provider: SourceProvider.ASHBY, externalId: 'blockhouse', name: 'Blockhouse' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'crossjoin-solutions',
    name: 'Crossjoin Solutions',
  },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'scorewarrior',
    name: 'Scorewarrior',
  },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'blacksmith agency',
    name: 'Blacksmith Agency',
  },
  { provider: SourceProvider.ASHBY, externalId: 'cartesia', name: 'Cartesia' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'normalcomputing',
    name: 'Normal Computing',
  },
  { provider: SourceProvider.ASHBY, externalId: 'cybret', name: 'Cybret' },
  { provider: SourceProvider.WORKABLE, externalId: 'runware', name: 'Runware' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'accepted-ltd',
    name: 'Accepted',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'localstack',
    name: 'LocalStack',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'squaredev', name: 'Squaredev' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'awesomemotive',
    name: 'Awesome Motive',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'salvo-software',
    name: 'Salvo Software',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'upkoi-inc', name: 'Upkoi' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'capgemini-insurance',
    name: 'Capgemini Insurance',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'shockbyte',
    name: 'Shockbyte',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'freedx', name: 'FreeDX' },
  { provider: SourceProvider.WORKABLE, externalId: 'boost', name: 'Boost' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'steadyvision',
    name: 'Steady Vision',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'sangoma-3', name: 'Sangoma' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'remotebase',
    name: 'Remotebase',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'hyperdev', name: 'Hyperdev' },
  { provider: SourceProvider.WORKABLE, externalId: 'salsita', name: 'Salsita' },
  { provider: SourceProvider.WORKABLE, externalId: 'clipt', name: 'Clipt' },
  { provider: SourceProvider.WORKABLE, externalId: 'action1', name: 'Action1' },
  { provider: SourceProvider.WORKABLE, externalId: 'netguru', name: 'Netguru' },
  { provider: SourceProvider.WORKABLE, externalId: 'ischool', name: 'iSchool' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'revive-media',
    name: 'Revive Media',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'createq-space',
    name: 'Createq',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'arcos', name: 'Arcos' },
  { provider: SourceProvider.WORKABLE, externalId: 'surglobal', name: 'Surglobal' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'hire-developer',
    name: 'Hire Developer',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'optimiza-4', name: 'Optimiza' },
  { provider: SourceProvider.WORKABLE, externalId: 'stio', name: 'STIO' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'symphony-solutions',
    name: 'Symphony Solutions',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'intellectsoft',
    name: 'Intellectsoft',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'mullers-solutions-1',
    name: "Muller's Solutions",
  },
  { provider: SourceProvider.WORKABLE, externalId: 'rubikal', name: 'Rubikal' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'peoplecert',
    name: 'PeopleCert',
  },
  { provider: SourceProvider.WORKABLE, externalId: '2c2p', name: '2C2P' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'creditstar',
    name: 'Creditstar',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'c-the-signs', name: 'C the Signs' },
  { provider: SourceProvider.WORKABLE, externalId: 'workstate', name: 'Workstate' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'tcp-software-1',
    name: 'TCP Software',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'cynet-corp', name: 'Cynet' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'altitude-pay',
    name: 'Altitude Pay',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'limepack', name: 'Limepack' },
  { provider: SourceProvider.WORKABLE, externalId: 'up-hellas-1', name: 'Up Hellas' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'unisongroup',
    name: 'Unison Group',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'elements', name: 'Elements' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'opendatajobs',
    name: 'Open Data Jobs',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'livestock-information',
    name: 'Livestock Information',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'mysociety', name: 'mySociety' },
  { provider: SourceProvider.WORKABLE, externalId: 'lengow', name: 'Lengow' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'bwise-media-ag',
    name: 'Bwise Media',
  },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'arpu-telecommunication-services',
    name: 'ARPU Telecommunication Services',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'cropx', name: 'CropX' },
  {
    provider: SourceProvider.WORKABLE,
    externalId: 'inventyou-ab',
    name: 'Inventyou',
  },
  { provider: SourceProvider.WORKABLE, externalId: 'meteor', name: 'Meteor' },
  { provider: SourceProvider.WORKABLE, externalId: 'altoros', name: 'Altoros' },
  { provider: SourceProvider.WORKABLE, externalId: 'monterail', name: 'Monterail' },
  { provider: SourceProvider.WORKABLE, externalId: 'quistor', name: 'Quistor' },
  { provider: SourceProvider.WORKABLE, externalId: 'innovatrics', name: 'Innovatrics' },
  { provider: SourceProvider.WORKABLE, externalId: 'techne', name: 'Techne' },
  { provider: SourceProvider.WORKABLE, externalId: 'huzzle', name: 'Huzzle' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'reddit', name: 'Reddit' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'xntltd', name: 'XNT' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'shipmonk', name: 'ShipMonk' },
  { provider: SourceProvider.GREENHOUSE, externalId: '6sense', name: '6sense' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'whitetech', name: 'WhiteTech' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'polyai', name: 'PolyAI' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'grafanalabs',
    name: 'Grafana Labs',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'alpaca', name: 'Alpaca' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'axon', name: 'Axon' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'lightmatter', name: 'Lightmatter' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'doctolib', name: 'Doctolib' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'horacemannservicecorporation',
    name: 'Horace Mann Service Corporation',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'gatikaiinc', name: 'Gatik' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'juullabs', name: 'JUUL Labs' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'futuresecureai',
    name: 'FutureSecure AI',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'paynearmeinc',
    name: 'PayNearMe',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'clarityinnovates',
    name: 'Clarity Innovations',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'tmg', name: 'TMG' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'groupon', name: 'Groupon' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'regscale', name: 'RegScale' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'eqtpartners', name: 'EQT' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'tomorrow', name: 'Tomorrow' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'cision', name: 'Cision' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'teachablecareers',
    name: 'Teachable',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'trase', name: 'Trase' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'clickhouse', name: 'ClickHouse' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'apptronik', name: 'Apptronik' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'gr8tech', name: 'GR8 Tech' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'armada', name: 'Armada' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'braze', name: 'Braze' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'nscaleoperationsukltd',
    name: 'Nscale Operations',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'sagentindia',
    name: 'Sagent India',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'doitintl', name: 'DoiT' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'hyphenconnect',
    name: 'Hyphen Connect',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'adyen', name: 'Adyen' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'dashlane', name: 'Dashlane' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: '10xgenomics',
    name: '10x Genomics',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'keyfactorinc',
    name: 'Keyfactor',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'recharge', name: 'Recharge' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'circleci', name: 'CircleCI' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'connectwise',
    name: 'ConnectWise',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'postman', name: 'Postman' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'intercom', name: 'Intercom' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'branch', name: 'Branch' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'sezzle', name: 'Sezzle' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'gympass', name: 'Gympass' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'stone', name: 'Stone' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'addepar1', name: 'Addepar' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'mixpanel', name: 'Mixpanel' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'centralreach',
    name: 'CentralReach',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'anthropic', name: 'Anthropic' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'niraenergy', name: 'Nira Energy' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'federato', name: 'Federato' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'amplitude', name: 'Amplitude' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'hightouch', name: 'Hightouch' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'gleanwork', name: 'Glean' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'remesh', name: 'Remesh' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'mercury', name: 'Mercury' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'omadahealth', name: 'Omada Health' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'stubhubinc', name: 'StubHub' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'aquaticcapitalmanagement',
    name: 'Aquatic Capital Management',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'heygen', name: 'HeyGen' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'thedutchie', name: 'Dutchie' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'givecampus', name: 'GiveCampus' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'headway', name: 'Headway' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'pilothq', name: 'Pilot' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'thinkingmachines',
    name: 'Thinking Machines',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'wonderschool',
    name: 'Wonderschool',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'merge', name: 'Merge' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'mongodb', name: 'MongoDB' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'patterndata',
    name: 'Pattern Data',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'novacredit',
    name: 'Nova Credit',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'gravitypayments17',
    name: 'Gravity Payments',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'deepmind', name: 'DeepMind' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'verkada', name: 'Verkada' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'zoo', name: 'Zoo' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'attentive', name: 'Attentive' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'impiricus', name: 'Impiricus' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'roku', name: 'Roku' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'aurorainnovation',
    name: 'Aurora Innovation',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'digitalocean98',
    name: 'DigitalOcean',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'ownwell', name: 'Ownwell' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'iterable', name: 'Iterable' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'newsela', name: 'Newsela' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'nirmata', name: 'Nirmata' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'oscar', name: 'Oscar' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'jazzx-ai', name: 'JazzX AI' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'fivetran', name: 'Fivetran' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'airbnb', name: 'Airbnb' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'cribl', name: 'Cribl' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'chime', name: 'Chime' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'formationbio',
    name: 'Formation Bio',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'imaginepediatrics',
    name: 'Imagine Pediatrics',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'nubank', name: 'Nubank' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'paveakatroveinformationtechnologies',
    name: 'Pave',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'stratacareers',
    name: 'Strata',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'glossgenius',
    name: 'GlossGenius',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'astranis', name: 'Astranis' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'extend', name: 'Extend' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'hatchcareers', name: 'Hatch' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'sonyinteractiveentertainmentglobal',
    name: 'Sony Interactive Entertainment',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'natera', name: 'Natera' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'forgeglobal',
    name: 'Forge Global',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'avride', name: 'Avride' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'justworks', name: 'Justworks' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'okta', name: 'Okta' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'latitude', name: 'Latitude' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'ezcaterinc', name: 'ezCater' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'hc360', name: 'HC360' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'optoinvest', name: 'Opto Investments' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'readysettechnologyinc',
    name: 'ReadySet',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'truveta', name: 'Truveta' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'peregrinetechnologies',
    name: 'Peregrine Technologies',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'smithrx', name: 'SmithRx' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'acuitymd', name: 'AcuityMD' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'gallup', name: 'Gallup' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'netlifyexplorecareers',
    name: 'Netlify',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'crexi', name: 'Crexi' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'navtechnologies',
    name: 'Nav',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'perfectserve', name: 'PerfectServe' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'lazarusenterprises',
    name: 'Lazarus Enterprises',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'newsbreak', name: 'NewsBreak' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'flip', name: 'Flip' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'dhigroupinc', name: 'DHI Group' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'coherehealth', name: 'Cohere Health' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'sixthstreet', name: 'Sixth Street' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'eleviassociates', name: 'Elevia' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'dnsfilter', name: 'DNSFilter' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'amwell', name: 'Amwell' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'sigmacomputing',
    name: 'Sigma Computing',
  },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'koboldmetalsdrc',
    name: 'KoBold Metals',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'takealotcom', name: 'takealot.com' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'nozominetworks',
    name: 'Nozomi Networks',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'cresta', name: 'Cresta' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'tebra', name: 'Tebra' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'apartmentiq', name: 'ApartmentIQ' },
  {
    provider: SourceProvider.GREENHOUSE,
    externalId: 'apertumonline',
    name: 'Apertum Online',
  },
  { provider: SourceProvider.GREENHOUSE, externalId: 'joyousteam', name: 'Joyous' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'nortal', name: 'Nortal' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'submer', name: 'SUBMER' },
  { provider: SourceProvider.GREENHOUSE, externalId: 'yunoenergy', name: 'Yuno Energy' },
  { provider: SourceProvider.ASHBY, externalId: 'breaker', name: 'Breaker' },
  { provider: SourceProvider.ASHBY, externalId: 'certifid', name: 'CertifID' },
  {
    provider: SourceProvider.ASHBY,
    externalId: 'constellationspace',
    name: 'Constellation Space',
  },
  { provider: SourceProvider.ASHBY, externalId: 'elastic-co', name: 'Elastic' },
  { provider: SourceProvider.ASHBY, externalId: 'honeybook', name: 'HoneyBook' },
  { provider: SourceProvider.ASHBY, externalId: 'litmus', name: 'Litmus' },
  { provider: SourceProvider.ASHBY, externalId: 'maven', name: 'Maven' },
  { provider: SourceProvider.ASHBY, externalId: 'mistral', name: 'Mistral' },
  { provider: SourceProvider.ASHBY, externalId: 'mutiny', name: 'Mutiny' },
  { provider: SourceProvider.ASHBY, externalId: 'nuon', name: 'Nuon' },
  { provider: SourceProvider.ASHBY, externalId: 'nutanix', name: 'Nutanix' },
  { provider: SourceProvider.ASHBY, externalId: 'polymath', name: 'Polymath' },
  { provider: SourceProvider.ASHBY, externalId: 'share', name: 'Share' },
  { provider: SourceProvider.ASHBY, externalId: 'sifflet', name: 'Sifflet' },
  { provider: SourceProvider.ASHBY, externalId: 'town', name: 'Town' },
];

